// <auto-generated />
namespace ForumDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Bas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bas));
        
        string IMigrationMetadata.Id
        {
            get { return "202003051548311_Bas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
